name: Build OTD plugin
on: [push, pull_request]
jobs:
  build:
    name: Build OTD plugin (${{matrix.os}}/${{matrix.config}})
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        config: [Release, Debug]
        os: [windows-2022, macos-26]
    steps:
      - uses: actions/checkout@v6
      - name: Fetch nuget packages
        run: dotnet restore
      - name: Build
        id: build
        shell: pwsh
        run: |
          $proj = [Xml](Get-Content -Raw OTDIPC/OTDIPC.csproj)
          $version = $proj.Project.PropertyGroup.AssemblyVersion
          $version = ($version -split '\.')[0..2] -join '.'
          $version = "$version.${{github.run_number}}"
          echo "Building version $version"
          
          dotnet msbuild OTDIPC.sln /p:Configuration="${{matrix.config}}" "/p:AssemblyVersion=$version"
          $out = "${{runner.temp}}/out"
          ./copy-artifacts.ps1 `
            -Configuration ${{matrix.config}} `
            -Version $version `
            -Out $out
          Add-Content $Env:GITHUB_OUTPUT "path=$out"
          Add-Content $Env:GITHUB_OUTPUT "version=$version"
      - name: Attach zip
        if: matrix.config != 'Debug' && matrix.os == 'windows-2022'
        uses: actions/upload-artifact@v6
        with:
          name: OpenKneeboard-OTD-IPC-v${{steps.build.outputs.version}}
          path: ${{steps.build.outputs.path}}/OpenKneeboard-OTD-IPC.zip
      - name: Attach debug symbols
        if: matrix.config != 'Debug' && matrix.os == 'windows-2022'
        uses: actions/upload-artifact@v6
        with:
          name: OpenKneeboard-OTD-IPC-DebugSymbols-v${{steps.build.outputs.version}}
          path: ${{steps.build.outputs.path}}/*.pdb
      - name: Create draft release
        id: create-release
        if: github.ref_type == 'tag' && matrix.config != 'Debug' && matrix.os == 'windows-2022'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}     
        with:
          release_name: ${{github.ref_name}}
          tag_name: ${{github.ref_name}}
          draft: true
          body: "Write release notes here"
      - name: Attach zip to release
        if: github.ref_type == 'tag' && matrix.config != 'Debug'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_name: OpenKneeboard-OTD-IPC-v${{steps.build.outputs.version}}.zip
          asset_path: ${{steps.build.outputs.path}}/OpenKneeboard-OTD-IPC.zip
          asset_content_type: application/zip
      - name: Attach debug symbols
        if: github.ref_type == 'tag' && matrix.config != 'Debug' && matrix.os == 'windows-2022'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_name: OpenKneeboard-OTD-IPC-DebugSymbols-v${{steps.build.outputs.version}}.zip
          asset_path: ${{steps.build.outputs.path}}/DebugSymbols.zip
          asset_content_type: application/zip
