name: Build OTD plugin
on: [push, pull_request]
jobs:
  build:
    name: Build OTD plugin (${{matrix.os}}/${{matrix.config}})
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        config: [Release, Debug]
        os: [windows-2022, macos-26]
    steps:
      - uses: actions/checkout@v6
      - name: Fetch nuget packages
        run: dotnet restore
      - name: Build
        id: build
        shell: pwsh
        run: |
          $proj = [Xml](Get-Content -Raw OTDIPC/OTDIPC.csproj)
          $version = $proj.Project.PropertyGroup.AssemblyVersion
          $version = ($version -split '\.')[0..2] -join '.'
          $version = "$version.${{github.run_number}}"
          echo "Building version $version"
          
          dotnet msbuild OTDIPC.sln /p:Configuration="${{matrix.config}}" "/p:AssemblyVersion=$version"
          $out = "${{runner.temp}}/out"
          ./copy-artifacts.ps1 `
            -Configuration ${{matrix.config}} `
            -Version $version `
            -Out $out
          Add-Content $Env:GITHUB_OUTPUT "path=$out"
          Add-Content $Env:GITHUB_OUTPUT "version=$version"
      - name: Attach zip
        if: matrix.config != 'Debug' && matrix.os == 'windows-2022'
        uses: actions/upload-artifact@v7
        with:
          name: OpenKneeboard-OTD-IPC-v${{steps.build.outputs.version}}
          path: ${{steps.build.outputs.path}}/OpenKneeboard-OTD-IPC.zip
      - name: Attach debug symbols
        if: matrix.config != 'Debug' && matrix.os == 'windows-2022'
        uses: actions/upload-artifact@v7
        with:
          name: OpenKneeboard-OTD-IPC-DebugSymbols-v${{steps.build.outputs.version}}
          path: ${{steps.build.outputs.path}}/*.pdb
