name: Continuous Integration
on: [push, pull_request]
jobs:
  build:
    name: Build (${{matrix.config}})
    runs-on: windows-2022
    strategy:
      matrix:
        config: [Release, Debug]
    steps:
      - uses: actions/checkout@v2
      - name: Fetch nuget packages
        run: dotnet restore
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        with:
          vs-version: '[17.2,)'
      - name: Build
        id: build
        run: |
          msbuild OTDIPC.sln /p:Configuration="${{matrix.config}}"
          $out = "${{runner.temp}}/out"
          ./copy-artifacts.ps1 `
            -Configuration ${{matrix.config}} `
            -Out $out `
            -BuildNumber $Env:GITHUB_RUN_NUMBER
          Add-Content $Env:GITHUB_OUTPUT "path=$out"
          Add-Content $Env:GITHUB_OUTPUT "version=$(Get-Content $out/version.txt)"
      - name: Attach zip
        if: matrix.config != 'Debug'
        uses: actions/upload-artifact@v3
        with:
          name: OpenKneeboard-OTD-IPC-v${{steps.build.outputs.version}}
          path: ${{steps.build.outputs.path}}/OpenKneeboard-OTD-IPC.zip
      - name: Attach test client
        if: matrix.config != 'Debug'
        uses: actions/upload-artifact@v3
        with:
          name: OpenKneeboard-OTD-IPC-TestClient-v${{steps.build.outputs.version}}
          path: ${{steps.build.outputs.path}}/OTDIPC-TestClient.exe
      - name: Attach debug symbols
        if: matrix.config != 'Debug'
        uses: actions/upload-artifact@v3
        with:
          name: OpenKneeboard-OTD-IPC-DebugSymbols-v${{steps.build.outputs.version}}
          path: ${{steps.build.outputs.path}}/*.pdb
