name: Continuous Integration
on: [push, pull_request]
jobs:
  build:
    name: Build (${{matrix.config}})
    runs-on: windows-2022
    strategy:
      matrix:
        config: [Release, Debug]
    steps:
      - uses: actions/checkout@v2
      - name: Fetch nuget packages
        run: dotnet restore
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        with:
          vs-version: '[17.2)'
      - name: Build
        run: msbuild OTDIPC.sln /p:Configuration="${{matrix.config}}"
