name: Continuous Integration
on: [push, pull_request]
jobs:
  build:
    name: Build (${{matrix.config}})
    runs-on: windows-2022
    strategy:
      matrix:
        config: [Release, Debug]
    steps:
      - uses: actions/checkout@v2
        with:
          path: source
      - name: Fetch nuget packages
        run: dotnet restore
      - name: Build
        run: msbuild OTDIPC.sln /p:Configuration="${{matrix.config}}"
